services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  grpc-server:
    build:
      context: .
      dockerfile: dockerfile-server
    depends_on:
      - mongo
    env_file: .env
    ports:
      - "50051:50051"

  flask-ui:
    build:
      context: .
      dockerfile: dockerfile-ui
    depends_on:
      - grpc-server
    env_file: .env
    environment:
      - GRPC_HOST=grpc-server
    ports:
      - "8080:8080"
